# Generated by Django 6.0.6 on 2026-07-21 18:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("LOGIN", "Login"),
                            ("LOGOUT", "Logout"),
                            ("CREATE", "Create"),
                            ("UPDATE", "Update"),
                            ("DELETE", "Delete"),
                            ("VIEW", "View"),
                            ("LIKE", "Like"),
                            ("UNLIKE", "Unlike"),
                            ("COMMENT", "Comment"),
                            ("REPORT", "Report"),
                            ("SAVE", "Save"),
                            ("UNSAVE", "Unsave"),
                            ("FOLLOW", "Follow"),
                            ("UNFOLLOW", "Unfollow"),
                            ("ACCEPT", "Accept"),
                            ("REJECT", "Reject"),
                            ("RESOLVE", "Resolve"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                ("object_id", models.UUIDField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=255)),
                ("request_path", models.CharField(blank=True, max_length=255)),
                ("request_method", models.CharField(blank=True, max_length=10)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activity_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Activity Log",
                "verbose_name_plural": "Activity Logs",
                "db_table": "activity_logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="activity_lo_user_id_b8c999_idx",
                    ),
                    models.Index(
                        fields=["action_type"], name="activity_lo_action__9e4610_idx"
                    ),
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="activity_lo_content_edc5bf_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="activity_lo_created_166e11_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ReportedItem",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("object_id", models.UUIDField()),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("SPAM", "Spam"),
                            ("HARASSMENT", "Harassment"),
                            ("INAPPROPRIATE", "Inappropriate Content"),
                            ("COPYRIGHT", "Copyright Infringement"),
                            ("PRIVACY", "Privacy Violation"),
                            ("OTHER", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Additional details from the reporter"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("UNDER_REVIEW", "Under Review"),
                            ("RESOLVED", "Resolved"),
                            ("DISMISSED", "Dismissed"),
                            ("NEEDS_INFO", "Needs More Info"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "resolution_note",
                    models.TextField(
                        blank=True, help_text="Moderator's note on the resolution"
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        limit_choices_to={
                            "model__in": [
                                "journey",
                                "journeyupdate",
                                "comment",
                                "commentreply",
                            ]
                        },
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "moderator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="moderated_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Reported Item",
                "verbose_name_plural": "Reported Items",
                "db_table": "reported_items",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="reported_it_content_3ab8bc_idx",
                    ),
                    models.Index(
                        fields=["status"], name="reported_it_status_52fb2e_idx"
                    ),
                    models.Index(
                        fields=["reporter"], name="reported_it_reporte_14aff3_idx"
                    ),
                    models.Index(
                        fields=["-created_at"], name="reported_it_created_ad6315_idx"
                    ),
                ],
            },
        ),
    ]
