# Generated by Django 6.0.6 on 2026-07-27 04:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0001_initial"),
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="reporteditem",
            name="ip_address",
            field=models.GenericIPAddressField(
                blank=True, help_text="IP address of the reporter", null=True
            ),
        ),
        migrations.AddField(
            model_name="reporteditem",
            name="user_agent",
            field=models.CharField(
                blank=True, help_text="User agent of the reporter", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="activitylog",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("LOGIN", "Login"),
                    ("LOGOUT", "Logout"),
                    ("REGISTER", "Register"),
                    ("VERIFY_EMAIL", "Verify Email"),
                    ("PASSWORD_RESET", "Password Reset"),
                    ("PASSWORD_CHANGE", "Password Change"),
                    ("CREATE", "Create"),
                    ("UPDATE", "Update"),
                    ("DELETE", "Delete"),
                    ("VIEW", "View"),
                    ("LIKE", "Like"),
                    ("UNLIKE", "Unlike"),
                    ("COMMENT", "Comment"),
                    ("REPLY", "Reply"),
                    ("FOLLOW", "Follow"),
                    ("UNFOLLOW", "Unfollow"),
                    ("SAVE", "Save"),
                    ("UNSAVE", "Unsave"),
                    ("REPORT", "Report"),
                    ("RESOLVE", "Resolve"),
                    ("SUSPEND", "Suspend"),
                    ("UNSUSPEND", "Unsuspend"),
                    ("BAN", "Ban"),
                    ("UNBAN", "Unban"),
                    ("ACCEPT", "Accept"),
                    ("REJECT", "Reject"),
                ],
                db_index=True,
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="activitylog",
            name="metadata",
            field=models.JSONField(
                blank=True, default=dict, help_text="Additional context as JSON"
            ),
        ),
        migrations.AlterField(
            model_name="reporteditem",
            name="reason",
            field=models.CharField(
                choices=[
                    ("SPAM", "Spam"),
                    ("HARASSMENT", "Harassment"),
                    ("INAPPROPRIATE", "Inappropriate Content"),
                    ("COPYRIGHT", "Copyright Infringement"),
                    ("PRIVACY", "Privacy Violation"),
                    ("OTHER", "Other"),
                ],
                db_index=True,
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="reporteditem",
            name="resolved_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name="activitylog",
            index=models.Index(
                fields=["user", "action_type"], name="activity_lo_user_id_d69053_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reporteditem",
            index=models.Index(
                fields=["status", "-created_at"], name="reported_it_status_6c32ec_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reporteditem",
            index=models.Index(
                fields=["reporter", "status"], name="reported_it_reporte_a83fd0_idx"
            ),
        ),
    ]
