# Generated by Django 6.0.6 on 2026-08-01 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0003_activitylog_updated_by_reporteditem_updated_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activitylog",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("LOGIN", "Login"),
                    ("LOGOUT", "Logout"),
                    ("REGISTER", "Register"),
                    ("VERIFY_EMAIL", "Verify Email"),
                    ("PASSWORD_RESET", "Password Reset"),
                    ("PASSWORD_CHANGE", "Password Change"),
                    ("CLEAR_DATA", "Clear Data"),
                    ("DELETE ACCOUNT", "Delete Account"),
                    ("CREATE", "Create"),
                    ("UPDATE", "Update"),
                    ("DELETE", "Delete"),
                    ("VIEW", "View"),
                    ("LIKE", "Like"),
                    ("UNLIKE", "Unlike"),
                    ("COMMENT", "Comment"),
                    ("REPLY", "Reply"),
                    ("FOLLOW", "Follow"),
                    ("UNFOLLOW", "Unfollow"),
                    ("SAVE", "Save"),
                    ("UNSAVE", "Unsave"),
                    ("REPORT", "Report"),
                    ("RESOLVE", "Resolve"),
                    ("SUSPEND", "Suspend"),
                    ("UNSUSPEND", "Unsuspend"),
                    ("BAN", "Ban"),
                    ("UNBAN", "Unban"),
                    ("ACCEPT", "Accept"),
                    ("REJECT", "Reject"),
                ],
                db_index=True,
                max_length=30,
            ),
        ),
    ]
