# Generated by Django 6.0.6 on 2026-07-27 04:57

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="avatar_public_id",
            field=models.CharField(
                blank=True,
                help_text="Cloudinary public ID for avatar management.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="avatar_url",
            field=models.URLField(
                blank=True, help_text="Cloudinary URL for avatar.", null=True
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="failed_login_attempts",
            field=models.IntegerField(
                default=0, help_text="Number of consecutive failed login attempts."
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="is_suspended",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether the user has been suspended by admin.",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="is_verified",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether the user has verified their email.",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="last_login_ip",
            field=models.GenericIPAddressField(
                blank=True, help_text="IP address of last login.", null=True
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="locked_until",
            field=models.DateTimeField(
                blank=True, help_text="Account lockout until this timestamp.", null=True
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="suspended_at",
            field=models.DateTimeField(
                blank=True, help_text="Timestamp when user was suspended.", null=True
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="suspension_reason",
            field=models.TextField(
                blank=True, help_text="Reason for user suspension.", null=True
            ),
        ),
        migrations.AddField(
            model_name="userpreference",
            name="allow_direct_messages",
            field=models.BooleanField(
                default=True, help_text="Allow users to send direct messages."
            ),
        ),
        migrations.AddField(
            model_name="userpreference",
            name="show_activity_status",
            field=models.BooleanField(
                default=True, help_text="Show when user is online."
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                help_text="DEPRECATED: Use avatar_url instead.",
                null=True,
                upload_to="profile_pictures/",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(db_index=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                db_index=True,
                max_length=30,
                unique=True,
                validators=[accounts.validators.validate_username],
            ),
        ),
        migrations.AlterField(
            model_name="userpreference",
            name="email_notifications",
            field=models.BooleanField(
                default=True, help_text="Receive email notifications."
            ),
        ),
        migrations.AlterField(
            model_name="userpreference",
            name="show_email",
            field=models.BooleanField(
                default=False, help_text="Display email on public profile."
            ),
        ),
        migrations.AlterField(
            model_name="userpreference",
            name="show_full_name",
            field=models.BooleanField(
                default=True, help_text="Display full name on public profile."
            ),
        ),
        migrations.AddIndex(
            model_name="follower",
            index=models.Index(
                fields=["follower"], name="user_follow_followe_a9075a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="follower",
            index=models.Index(
                fields=["following"], name="user_follow_followi_1e25dd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="follower",
            index=models.Index(
                fields=["follower", "following"], name="user_follow_followe_4ec440_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["email"], name="users_email_4b85f2_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["username"], name="users_usernam_baeb4b_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["-created_at"], name="users_created_30b417_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["is_verified", "is_active"], name="users_is_veri_11b510_idx"
            ),
        ),
    ]
