# Generated by Django 6.0.6 on 2026-07-27 08:56

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_profile_avatar_public_id_profile_avatar_url_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="avatar_public_id",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="avatar_url",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="profile_picture",
        ),
        migrations.AddField(
            model_name="profile",
            name="avatar",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="avatar"
            ),
        ),
    ]
