# Generated by Django 6.0.6 on 2026-07-27 04:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        (
            "journey",
            "0002_remove_acceptedsolution_accepted_so_accepte_6fe4e5_idx_and_more",
        ),
        ("reaction", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AcceptedSolution",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("accepted_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "verbose_name": "Accepted Solution",
                "verbose_name_plural": "Accepted Solutions",
                "db_table": "accepted_solutions",
            },
        ),
        migrations.CreateModel(
            name="SavedUpdate",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
            options={
                "verbose_name": "Saved Update",
                "verbose_name_plural": "Saved Updates",
                "db_table": "saved_updates",
            },
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("LIKE", "Like"),
                    ("COMMENT", "Comment"),
                    ("COMMENT_REPLY", "Comment Reply"),
                    ("FOLLOW", "Follow"),
                    ("ACCEPTED_SOLUTION", "Accepted Solution"),
                    ("MILESTONE", "Milestone"),
                ],
                db_index=True,
                max_length=30,
            ),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["journey_update", "-created_at"],
                name="comments_journey_461cc3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="commentreply",
            index=models.Index(
                fields=["comment", "-created_at"], name="comment_rep_comment_7897d4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="like",
            index=models.Index(
                fields=["user", "journey_update"], name="likes_user_id_d08af1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["recipient", "notification_type"],
                name="notificatio_recipie_b1a229_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="savedjourney",
            index=models.Index(
                fields=["-created_at"], name="saved_journ_created_f63777_idx"
            ),
        ),
        migrations.AddField(
            model_name="acceptedsolution",
            name="accepted_by",
            field=models.ForeignKey(
                blank=True,
                help_text="The user who accepted the solution (should be journey owner).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="accepted_solutions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="acceptedsolution",
            name="comment",
            field=models.OneToOneField(
                help_text="The comment that was accepted as the solution.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="accepted_for",
                to="reaction.comment",
            ),
        ),
        migrations.AddField(
            model_name="acceptedsolution",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="acceptedsolution",
            name="journey_update",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="accepted_solution",
                to="journey.journeyupdate",
            ),
        ),
        migrations.AddField(
            model_name="savedupdate",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="savedupdate",
            name="update",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="saved_by",
                to="journey.journeyupdate",
            ),
        ),
        migrations.AddField(
            model_name="savedupdate",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="saved_updates",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="acceptedsolution",
            index=models.Index(
                fields=["accepted_at"], name="accepted_so_accepte_6fe4e5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="acceptedsolution",
            index=models.Index(
                fields=["accepted_by"], name="accepted_so_accepte_d15088_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="savedupdate",
            index=models.Index(
                fields=["user", "-created_at"], name="saved_updat_user_id_84896f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="savedupdate",
            index=models.Index(
                fields=["update"], name="saved_updat_update__6ea939_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="savedupdate",
            index=models.Index(
                fields=["user", "update"], name="saved_updat_user_id_59a8b3_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="savedupdate",
            constraint=models.UniqueConstraint(
                fields=("user", "update"), name="unique_saved_update_per_user"
            ),
        ),
    ]
