# Generated by Django 6.0.6 on 2026-07-21 18:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BuilderScore",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "consistency_score",
                    models.PositiveIntegerField(
                        default=0, help_text="Daily engagement & streak"
                    ),
                ),
                (
                    "engagement_score",
                    models.PositiveIntegerField(
                        default=0, help_text="Interactions with others"
                    ),
                ),
                (
                    "milestone_score",
                    models.PositiveIntegerField(
                        default=0, help_text="Completing journey milestones"
                    ),
                ),
                (
                    "influence_score",
                    models.PositiveIntegerField(
                        default=0, help_text="Accepted solutions, follower count"
                    ),
                ),
                (
                    "total_score",
                    models.PositiveIntegerField(
                        default=0, help_text="Sum of all category scores"
                    ),
                ),
                ("level", models.PositiveSmallIntegerField(db_index=True, default=1)),
                (
                    "experience_points",
                    models.PositiveIntegerField(
                        default=0, help_text="XP for levelling"
                    ),
                ),
                ("next_level_xp", models.PositiveIntegerField(default=100)),
                (
                    "rank",
                    models.PositiveIntegerField(
                        default=0, help_text="Global rank (updated periodically)"
                    ),
                ),
                ("current_streak", models.PositiveSmallIntegerField(default=0)),
                ("longest_streak", models.PositiveSmallIntegerField(default=0)),
                ("last_activity_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="builder_score",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Builder Score",
                "verbose_name_plural": "Builder Scores",
                "db_table": "builder_scores",
                "indexes": [
                    models.Index(
                        fields=["user"], name="builder_sco_user_id_b30dfe_idx"
                    ),
                    models.Index(
                        fields=["total_score"], name="builder_sco_total_s_d151da_idx"
                    ),
                    models.Index(fields=["level"], name="builder_sco_level_e27ab9_idx"),
                    models.Index(fields=["rank"], name="builder_sco_rank_2b8d97_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="BuilderScoreHistory",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("CONSISTENCY", "Consistency"),
                            ("ENGAGEMENT", "Engagement"),
                            ("MILESTONE", "Milestone"),
                            ("INFLUENCE", "Influence"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "delta",
                    models.IntegerField(
                        help_text="Change amount (positive or negative)"
                    ),
                ),
                ("old_value", models.PositiveIntegerField()),
                ("new_value", models.PositiveIntegerField()),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("JOURNEY_CREATED", "Journey Created"),
                            ("UPDATE_ADDED", "Journey Update Added"),
                            ("SOLUTION_ACCEPTED", "Accepted Solution"),
                            ("COMMENT_RECEIVED", "Received Comment"),
                            ("LIKE_RECEIVED", "Received Like"),
                            ("MILESTONE_COMPLETED", "Milestone Completed"),
                            ("SAVED_JOURNEY", "Saved a Journey"),
                            ("FOLLOWED", "Followed by someone"),
                            ("DAILY_LOGIN", "Daily Login"),
                            ("BADGE_EARNED", "Earned a Badge"),
                            ("JOURNEY_DELETED", "Journey Deleted"),
                            ("UPDATE_DELETED", "Update Deleted"),
                            ("UNLIKED", "Unliked"),
                            ("COMMENT_REMOVED", "Comment Removed"),
                            ("REPORTED", "Reported"),
                        ],
                        max_length=50,
                    ),
                ),
                ("related_obj_id", models.UUIDField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=255)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "related_obj_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="score_histories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Builder Score History",
                "verbose_name_plural": "Builder Score Histories",
                "db_table": "builder_score_histories",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="builder_sco_user_id_e0a7f5_idx",
                    ),
                    models.Index(
                        fields=["user", "category"],
                        name="builder_sco_user_id_751fc6_idx",
                    ),
                    models.Index(
                        fields=["reason"], name="builder_sco_reason_483c3a_idx"
                    ),
                    models.Index(
                        fields=["related_obj_type", "related_obj_id"],
                        name="builder_sco_related_b4141e_idx",
                    ),
                ],
            },
        ),
    ]
