# Generated by Django 6.0.6 on 2026-07-21 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("score", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="builderscorehistory",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="builderscorehistory",
            name="user_agent",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
