# Generated by Django 6.0.6 on 2026-07-27 04:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("score", "0002_alter_builderscorehistory_ip_address_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="builderscore",
            name="comments_today",
            field=models.PositiveSmallIntegerField(
                default=0, help_text="Number of comments posted today"
            ),
        ),
        migrations.AddField(
            model_name="builderscore",
            name="last_comment_date",
            field=models.DateField(
                blank=True, help_text="Last date for comment count tracking", null=True
            ),
        ),
        migrations.AddField(
            model_name="builderscore",
            name="last_update_date",
            field=models.DateField(
                blank=True, help_text="Last date for update count tracking", null=True
            ),
        ),
        migrations.AddField(
            model_name="builderscore",
            name="updates_today",
            field=models.PositiveSmallIntegerField(
                default=0, help_text="Number of updates posted today"
            ),
        ),
        migrations.AlterField(
            model_name="builderscore",
            name="consistency_score",
            field=models.PositiveIntegerField(
                db_index=True, default=0, help_text="Daily engagement & streak"
            ),
        ),
        migrations.AlterField(
            model_name="builderscore",
            name="current_streak",
            field=models.PositiveSmallIntegerField(
                default=0, help_text="Current consecutive days with activity"
            ),
        ),
        migrations.AlterField(
            model_name="builderscore",
            name="engagement_score",
            field=models.PositiveIntegerField(
                db_index=True, default=0, help_text="Interactions with others"
            ),
        ),
        migrations.AlterField(
            model_name="builderscore",
            name="experience_points",
            field=models.PositiveIntegerField(default=0, help_text="XP for leveling"),
        ),
        migrations.AlterField(
            model_name="builderscore",
            name="influence_score",
            field=models.PositiveIntegerField(
                db_index=True, default=0, help_text="Accepted solutions, follower count"
            ),
        ),
        migrations.AlterField(
            model_name="builderscore",
            name="last_activity_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Last activity timestamp for streak calculation",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="builderscore",
            name="longest_streak",
            field=models.PositiveSmallIntegerField(
                default=0, help_text="Longest streak achieved"
            ),
        ),
        migrations.AlterField(
            model_name="builderscore",
            name="milestone_score",
            field=models.PositiveIntegerField(
                db_index=True, default=0, help_text="Completing journey milestones"
            ),
        ),
        migrations.AlterField(
            model_name="builderscore",
            name="next_level_xp",
            field=models.PositiveIntegerField(
                default=100, help_text="XP needed for next level"
            ),
        ),
        migrations.AlterField(
            model_name="builderscore",
            name="rank",
            field=models.PositiveIntegerField(
                db_index=True, default=0, help_text="Global rank (updated periodically)"
            ),
        ),
        migrations.AlterField(
            model_name="builderscore",
            name="total_score",
            field=models.PositiveIntegerField(
                db_index=True, default=0, help_text="Sum of all category scores"
            ),
        ),
        migrations.AlterField(
            model_name="builderscorehistory",
            name="category",
            field=models.CharField(
                choices=[
                    ("CONSISTENCY", "Consistency"),
                    ("ENGAGEMENT", "Engagement"),
                    ("MILESTONE", "Milestone"),
                    ("INFLUENCE", "Influence"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="builderscorehistory",
            name="reason",
            field=models.CharField(
                choices=[
                    ("JOURNEY_CREATED", "Journey Created"),
                    ("UPDATE_ADDED", "Journey Update Added"),
                    ("SOLUTION_ACCEPTED", "Accepted Solution"),
                    ("COMMENT_RECEIVED", "Received Comment"),
                    ("LIKE_RECEIVED", "Received Like"),
                    ("MILESTONE_COMPLETED", "Milestone Completed"),
                    ("SAVED_JOURNEY", "Saved a Journey"),
                    ("FOLLOWED", "Followed by someone"),
                    ("DAILY_LOGIN", "Daily Login"),
                    ("BADGE_EARNED", "Earned a Badge"),
                    ("STREAK_BONUS", "Streak Bonus"),
                    ("JOURNEY_DELETED", "Journey Deleted"),
                    ("UPDATE_DELETED", "Update Deleted"),
                    ("UNLIKED", "Unliked"),
                    ("COMMENT_REMOVED", "Comment Removed"),
                    ("REPORTED", "Reported"),
                ],
                db_index=True,
                max_length=50,
            ),
        ),
        migrations.AddIndex(
            model_name="builderscore",
            index=models.Index(
                fields=["consistency_score"], name="builder_sco_consist_ded445_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="builderscore",
            index=models.Index(
                fields=["engagement_score"], name="builder_sco_engagem_64a8cf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="builderscore",
            index=models.Index(
                fields=["milestone_score"], name="builder_sco_milesto_8b02a8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="builderscore",
            index=models.Index(
                fields=["influence_score"], name="builder_sco_influen_6b7f03_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="builderscorehistory",
            index=models.Index(
                fields=["-created_at"], name="builder_sco_created_094c84_idx"
            ),
        ),
    ]
