# Generated by Django 6.0.6 on 2026-07-19 18:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=50, unique=True)),
                ("slug", models.SlugField(max_length=60, unique=True)),
                ("usage_count", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Tag",
                "verbose_name_plural": "Tags",
                "db_table": "journey_tags",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Journey",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("PROGRAMMING", "Programming"),
                            ("FITNESS", "Fitness"),
                            ("TRAVEL", "Travel"),
                            ("BUSINESS", "Business"),
                            ("EDUCATION", "Education"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=30,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="journey-cover/"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("COMPLETED", "Completed"),
                            ("PAUSED", "Paused"),
                            ("ARCHIVED", "Archived"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("PUBLIC", "Public"),
                            ("FOLLOWERS", "Followers"),
                            ("PRIVATE", "Private"),
                        ],
                        default="PUBLIC",
                        max_length=20,
                    ),
                ),
                ("update_count", models.PositiveIntegerField(default=0)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deleted_journeys",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="journeys",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Journey",
                "verbose_name_plural": "Journeys",
                "db_table": "journeys",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="JourneyUpdate",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("description", models.TextField()),
                (
                    "milestone_status",
                    models.CharField(
                        choices=[
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="IN_PROGRESS",
                        max_length=20,
                    ),
                ),
                ("help_needed", models.BooleanField(default=False)),
                ("like_count", models.PositiveIntegerField(default=0)),
                ("comment_count", models.PositiveIntegerField(default=0)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deleted_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "journey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updates",
                        to="journey.journey",
                    ),
                ),
            ],
            options={
                "verbose_name": "Journey Update",
                "verbose_name_plural": "Journey Updates",
                "db_table": "journey_updates",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="JourneyImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("cloudinary_url", models.URLField(max_length=500)),
                ("cloudinary_public_id", models.CharField(max_length=255, unique=True)),
                ("width", models.PositiveIntegerField()),
                ("height", models.PositiveIntegerField()),
                ("order_index", models.PositiveSmallIntegerField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "journey_update",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="journey.journeyupdate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Journey Image",
                "verbose_name_plural": "Journey Images",
                "db_table": "journey_images",
                "ordering": ("order_index", "created_at"),
            },
        ),
        migrations.CreateModel(
            name="JourneyUpdateSolution",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("content", models.TextField()),
                ("like_count", models.PositiveIntegerField(default=0)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="journey_solutions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "journey_update",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="solutions",
                        to="journey.journeyupdate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Journey Solution",
                "verbose_name_plural": "Journey Solutions",
                "db_table": "journey_update_solutions",
                "ordering": ("created_at",),
            },
        ),
        migrations.CreateModel(
            name="AcceptedSolution",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("accepted_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "accepted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="accepted_solutions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "journey_update",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accepted_solution",
                        to="journey.journeyupdate",
                    ),
                ),
                (
                    "solution",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accepted_for",
                        to="journey.journeyupdatesolution",
                    ),
                ),
            ],
            options={
                "verbose_name": "Accepted Solution",
                "verbose_name_plural": "Accepted Solutions",
                "db_table": "accepted_solutions",
            },
        ),
        migrations.CreateModel(
            name="JourneyUpdateTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "journey_update",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tags",
                        to="journey.journeyupdate",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="journey_updates",
                        to="journey.tag",
                    ),
                ),
            ],
            options={
                "verbose_name": "Journey Update Tag",
                "verbose_name_plural": "Journey Update Tags",
                "db_table": "journey_update_tags",
            },
        ),
        migrations.AddIndex(
            model_name="journey",
            index=models.Index(fields=["owner"], name="journeys_owner_i_8712e3_idx"),
        ),
        migrations.AddIndex(
            model_name="journey",
            index=models.Index(fields=["status"], name="journeys_status_137fed_idx"),
        ),
        migrations.AddIndex(
            model_name="journey",
            index=models.Index(
                fields=["visibility"], name="journeys_visibil_e5f5cc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="journey",
            index=models.Index(fields=["category"], name="journeys_categor_dc58d0_idx"),
        ),
        migrations.AddIndex(
            model_name="journey",
            index=models.Index(
                fields=["-created_at"], name="journeys_created_ca5edf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="journey",
            index=models.Index(
                fields=["owner", "visibility"], name="journeys_owner_i_d27054_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="journeyupdate",
            index=models.Index(
                fields=["journey"], name="journey_upd_journey_9e2df3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="journeyupdate",
            index=models.Index(
                fields=["journey", "-created_at"], name="journey_upd_journey_895a25_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="journeyupdate",
            index=models.Index(
                fields=["help_needed"], name="journey_upd_help_ne_74081b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="journeyupdate",
            index=models.Index(
                fields=["milestone_status"], name="journey_upd_milesto_2303d6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="journeyupdate",
            index=models.Index(
                fields=["is_deleted"], name="journey_upd_is_dele_58f255_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="journeyimage",
            index=models.Index(
                fields=["journey_update"], name="journey_ima_journey_5234b1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="journeyimage",
            index=models.Index(
                fields=["order_index"], name="journey_ima_order_i_5065a0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="journeyupdatesolution",
            index=models.Index(
                fields=["journey_update"], name="journey_upd_journey_89a1b2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="journeyupdatesolution",
            index=models.Index(
                fields=["author"], name="journey_upd_author__cf358d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="acceptedsolution",
            index=models.Index(
                fields=["accepted_at"], name="accepted_so_accepte_6fe4e5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="acceptedsolution",
            index=models.Index(
                fields=["accepted_by"], name="accepted_so_accepte_d15088_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="journeyupdatetag",
            index=models.Index(fields=["tag"], name="journey_upd_tag_id_1acd75_idx"),
        ),
        migrations.AddIndex(
            model_name="journeyupdatetag",
            index=models.Index(
                fields=["journey_update"], name="journey_upd_journey_bc3a1c_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="journeyupdatetag",
            constraint=models.UniqueConstraint(
                fields=("journey_update", "tag"), name="unique_journey_update_tag"
            ),
        ),
    ]
