# Generated by Django 6.0.6 on 2026-07-27 04:57

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import journey.validators
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journey", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="acceptedsolution",
            name="accepted_so_accepte_6fe4e5_idx",
        ),
        migrations.RemoveIndex(
            model_name="acceptedsolution",
            name="accepted_so_accepte_d15088_idx",
        ),
        migrations.RemoveIndex(
            model_name="journeyupdatesolution",
            name="journey_upd_journey_89a1b2_idx",
        ),
        migrations.RemoveIndex(
            model_name="journeyupdatesolution",
            name="journey_upd_author__cf358d_idx",
        ),
        migrations.AlterModelOptions(
            name="tag",
            options={
                "ordering": ("-usage_count", "name"),
                "verbose_name": "Tag",
                "verbose_name_plural": "Tags",
            },
        ),
        migrations.RemoveIndex(
            model_name="journey",
            name="journeys_owner_i_8712e3_idx",
        ),
        migrations.RemoveIndex(
            model_name="journey",
            name="journeys_status_137fed_idx",
        ),
        migrations.RemoveIndex(
            model_name="journey",
            name="journeys_visibil_e5f5cc_idx",
        ),
        migrations.RemoveIndex(
            model_name="journey",
            name="journeys_owner_i_d27054_idx",
        ),
        migrations.RemoveIndex(
            model_name="journeyimage",
            name="journey_ima_journey_5234b1_idx",
        ),
        migrations.RemoveIndex(
            model_name="journeyimage",
            name="journey_ima_order_i_5065a0_idx",
        ),
        migrations.RemoveIndex(
            model_name="journeyupdate",
            name="journey_upd_journey_9e2df3_idx",
        ),
        migrations.RemoveIndex(
            model_name="journeyupdate",
            name="journey_upd_help_ne_74081b_idx",
        ),
        migrations.RemoveIndex(
            model_name="journeyupdate",
            name="journey_upd_is_dele_58f255_idx",
        ),
        migrations.RemoveIndex(
            model_name="journeyupdatetag",
            name="journey_upd_tag_id_1acd75_idx",
        ),
        migrations.RemoveIndex(
            model_name="journeyupdatetag",
            name="journey_upd_journey_bc3a1c_idx",
        ),
        migrations.AddField(
            model_name="journey",
            name="cover_image_public_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="journey",
            name="cover_image_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="journey",
            name="latest_progress",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="journeyupdate",
            name="progress_percentage",
            field=models.PositiveSmallIntegerField(
                default=0, validators=[django.core.validators.MaxValueValidator(100)]
            ),
        ),
        migrations.AddField(
            model_name="journeyupdate",
            name="trending_score",
            field=models.FloatField(
                db_index=True,
                default=0,
                help_text="Precomputed trending score for feed sorting.",
            ),
        ),
        migrations.AddField(
            model_name="journeyupdate",
            name="visibility",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PUBLIC", "Public"),
                    ("FOLLOWERS", "Followers"),
                    ("PRIVATE", "Private"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="tag",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tag",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="tag",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="journey",
            name="category",
            field=models.CharField(
                choices=[
                    ("SOFTWARE", "Software"),
                    ("STARTUP", "Startup"),
                    ("SKILL", "Skill"),
                    ("RESEARCH", "Research"),
                    ("BOOK", "Book"),
                    ("ART", "Art"),
                    ("FITNESS", "Fitness"),
                    ("DIY", "DIY"),
                    ("CONTENT", "Content"),
                    ("CHALLENGE", "Challenge"),
                    ("OTHER", "Other"),
                ],
                db_index=True,
                default="OTHER",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="journey",
            name="cover_image",
            field=models.ImageField(
                blank=True,
                help_text="DEPRECATED: Use cover_image_url instead.",
                null=True,
                upload_to="journey-cover/",
            ),
        ),
        migrations.AlterField(
            model_name="journey",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="journey",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("COMPLETED", "Completed"),
                    ("PAUSED", "Paused"),
                    ("ABANDONED", "Abandoned"),
                ],
                db_index=True,
                default="ACTIVE",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="journey",
            name="title",
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="journey",
            name="visibility",
            field=models.CharField(
                choices=[
                    ("PUBLIC", "Public"),
                    ("FOLLOWERS", "Followers"),
                    ("PRIVATE", "Private"),
                ],
                db_index=True,
                default="PUBLIC",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="journeyimage",
            name="cloudinary_public_id",
            field=models.CharField(
                max_length=255,
                unique=True,
                validators=[journey.validators.validate_cloudinary_public_id],
            ),
        ),
        migrations.AlterField(
            model_name="journeyimage",
            name="height",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="journeyimage",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="journeyimage",
            name="order_index",
            field=models.PositiveSmallIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name="journeyimage",
            name="width",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="journeyupdate",
            name="description",
            field=models.TextField(help_text="Sanitized HTML content."),
        ),
        migrations.AlterField(
            model_name="journeyupdate",
            name="help_needed",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="journeyupdate",
            name="like_count",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name="journeyupdate",
            name="milestone_status",
            field=models.CharField(
                choices=[
                    ("NONE", "None"),
                    ("MILESTONE", "Milestone"),
                    ("COMPLETED", "Completed"),
                ],
                db_index=True,
                default="NONE",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="journeyupdate",
            name="title",
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="tag",
            name="usage_count",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddIndex(
            model_name="journey",
            index=models.Index(
                fields=["owner", "-created_at"], name="journeys_owner_i_3951dc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="journey",
            index=models.Index(
                fields=["status", "visibility"], name="journeys_status_11f293_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="journey",
            index=models.Index(
                fields=["owner", "visibility", "is_deleted"],
                name="journeys_owner_i_67326f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="journey",
            index=models.Index(
                condition=models.Q(("is_deleted", False)),
                fields=["title", "description"],
                name="journey_search_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="journeyimage",
            index=models.Index(
                fields=["journey_update", "order_index"],
                name="journey_ima_journey_4ca1b7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="journeyimage",
            index=models.Index(
                fields=["cloudinary_public_id"], name="journey_ima_cloudin_024e89_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="journeyupdate",
            index=models.Index(
                fields=["help_needed", "is_deleted"],
                name="journey_upd_help_ne_071531_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="journeyupdate",
            index=models.Index(
                fields=["-created_at"], name="journey_upd_created_bfd476_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="journeyupdate",
            index=models.Index(
                condition=models.Q(("visibility__isnull", False)),
                fields=["visibility"],
                name="journey_visibility_partial_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="journeyupdate",
            index=models.Index(
                fields=["visibility", "is_deleted", "-created_at"],
                name="update_feed_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="journeyupdate",
            index=models.Index(
                condition=models.Q(("help_needed", True), ("is_deleted", False)),
                fields=["-created_at"],
                name="help_needed_feed_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="journeyupdate",
            index=models.Index(
                condition=models.Q(("is_deleted", False)),
                fields=["title", "description"],
                name="update_search_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="journeyupdatetag",
            index=models.Index(
                fields=["tag", "journey_update"], name="journey_upd_tag_id_845355_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tag",
            index=models.Index(fields=["name"], name="journey_tag_name_59fe23_idx"),
        ),
        migrations.AddIndex(
            model_name="tag",
            index=models.Index(fields=["slug"], name="journey_tag_slug_b0b46f_idx"),
        ),
        migrations.AddIndex(
            model_name="tag",
            index=models.Index(
                fields=["-usage_count"], name="journey_tag_usage_c_1c0d8f_idx"
            ),
        ),
        migrations.RemoveField(
            model_name="journeyupdatesolution",
            name="author",
        ),
        migrations.RemoveField(
            model_name="journeyupdatesolution",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="journeyupdatesolution",
            name="journey_update",
        ),
        migrations.DeleteModel(
            name="AcceptedSolution",
        ),
        migrations.DeleteModel(
            name="JourneyUpdateSolution",
        ),
    ]
