# Generated by Django 6.0.6 on 2026-07-27 08:56

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "journey",
            "0002_remove_acceptedsolution_accepted_so_accepte_6fe4e5_idx_and_more",
        ),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="journeyimage",
            name="journey_ima_cloudin_024e89_idx",
        ),
        migrations.RemoveField(
            model_name="journey",
            name="cover_image_public_id",
        ),
        migrations.RemoveField(
            model_name="journey",
            name="cover_image_url",
        ),
        migrations.AddField(
            model_name="journeyimage",
            name="image",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="image"
            ),
        ),
        migrations.AlterField(
            model_name="journey",
            name="cover_image",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="cover_image"
            ),
        ),
        migrations.RemoveField(
            model_name="journeyimage",
            name="cloudinary_public_id",
        ),
        migrations.RemoveField(
            model_name="journeyimage",
            name="cloudinary_url",
        ),
    ]
