# Generated by Django 6.0.6 on 2026-07-27 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("journey", "0003_remove_journeyimage_journey_ima_cloudin_024e89_idx_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="journeyimage",
            name="height",
        ),
        migrations.RemoveField(
            model_name="journeyimage",
            name="width",
        ),
    ]
